const MARK_AS_READ = "MARK_AS_READ";
const SET_TYPE_FILTER = "SET_TYPE_FILTER";
const URGENT = "URGENT";
const DEFAULT = "DEFAULT";
const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";

const NotificationTypeFilters = {URGENT, DEFAULT};

module.exports = {MARK_AS_READ, SET_TYPE_FILTER, URGENT, DEFAULT, FETCH_NOTIFICATIONS_SUCCESS};