
const SELECT_COURSE = 'SELECT_COURSE'
const UNSELECT_COURSE = 'UNSELECT_COURSE'
const FETCH_COURSE_SELECT = 'FETCH_COURSE_SELECT'

module.exports = {SELECT_COURSE, UNSELECT_COURSE, FETCH_COURSE_SELECT}